kernel:
  image: linuxkit/kernel:4.14.63
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.6
  - linuxkit/runc:v0.6
  - linuxkit/containerd:v0.6
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:v0.6
    env:
     - INSECURE=true
  - name: influxdb
    image: influxdb:1.4
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
  - name: kapacitor
    image: kapacitor:1.4
    net: host
    capabilities:
      - all
    env:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  - name: telegraf
    image: telegraf:1.4
    net: host
    capabilities:
      - all
  - name: chronograf
    image: chronograf:1.4
    net: host
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_DAC_OVERRIDE
    env:
      - INFLUXDB_URL=http://localhost:8086
      - KAPACITOR_URL=http://localhost:9092
trust:
  org:
    - linuxkit
    - library
