kernel:
  image: linuxkit/kernel:4.14.63
  cmdline: "console=ttyS0"
init:
  - linuxkit/init:v0.6
  - linuxkit/runc:v0.6
  - linuxkit/containerd:v0.6
onboot:
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount-vpnkit
    image: alpine:3.8
    binds:
        - /var/:/host_var:rbind,rshared
    capabilities:
        - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
services:
  - name: sshd
    image: linuxkit/sshd:v0.6
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:v0.6
    binds:
        - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]

files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true

trust:
  org:
    - linuxkit
