#!/bin/sh

CALIBRATION_FOLDER_DEFAULT="/tmp"

usage()
{
    echo "Usage: $0 <BW> <ANT> <FRE> <CAL_FOLDER(optional)>"
    echo ""
    echo "    Extract the Baseband RX attenuation settings from the calibration files"
    echo ""
    echo "    BW            BandWidth"
    echo "    ANT           Antenna selection [1,2]"
    echo "    FREQ          Frequency of BB RX"
    echo "    CAL_FOLDER    (optional) Calibration folder, default folder: /tmp"
    exit 1
}

#################  Check and Get Arguments  #####################
if [ "$#" -eq 4 ]; then
    BW=$1
    ANT=$2
    RX_FREQ=$3
    CAL_FOLDER=$4
elif [ "$#" -eq 3 ]; then
    BW=$1
    ANT=$2
    RX_FREQ=$3
    CAL_FOLDER=$CALIBRATION_FOLDER_DEFAULT
else
    echo "$0 - Error : Invalid number of argument $#"
    >&2 usage
fi

#################  Find Band  #####################
if [ ${RX_FREQ} -ge 703 ] && [ ${RX_FREQ} -le 748 ]; then
    BAND=28
elif [ ${RX_FREQ} -ge 824 ] && [ ${RX_FREQ} -le 849 ]; then
    BAND=5
elif [ ${RX_FREQ} -ge 1710 ] && [ ${RX_FREQ} -le 1785 ]; then
    BAND=3
else
    #Implement your band above
    BAND=0
fi

##################  Get Calibaration file  ######################
CAL_FNAME="$CAL_FOLDER/bbrxatten_b${BAND}_${BW}_ant${ANT}.cal"

#################  Check Calibaration file  #####################
if [ ! -e ${CAL_FNAME} ]; then
    echo "$0 - Error : The file $CAL_FNAME not found!"
    exit 1
fi

################### Get Attenuation value########################
ATT_TO_SET=$(cal-getbbatt ${BW} ${ANT} ${RX_FREQ} ${CAL_FNAME} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error : $ATT_TO_SET"
    exit 1
fi

echo $ATT_TO_SET
