#!/bin/sh

FREQ_LINE=1
CAL_OFFSET_LINE=2

#source /tmp/system.conf

usage()
{
    echo "Usage: $0 <BW> <ANT> <FRE> <CAL_FILE>"
    echo ""
    echo "    Extract the Baseband (TX/RX) attenuation settings from the calibration files"
    echo ""
    echo "    BW          BandWidth"
    echo "    ANT         Antenna selection [1,2]"
    echo "    FREQ        Frequency of BB RX"
    echo "    CAL_FILE    Calibration file"
    exit 1
}

#################  Check and Get Arguments  #####################
if [ "$#" -eq 4 ]; then
    BW=$1
    ANT=$2
    RX_FREQ=$3
    CAL_FNAME=$4
else
    echo "$0 - Invalid number of argument $#"
    >&2 usage
fi

#################  Check Antenna Arguments  #####################                                        
if [ ${ANT} -ne "1" ] && [ ${ANT} -ne "2" ]; then
    echo "$0 - Invalid antenna selection."
    >&2 usage
fi

#################  Check Calibaration file  #####################
if [ ! -e ${CAL_FNAME} ]; then
    echo "$0 - The file $CAL_FNAME not found!"
    exit 1
fi

#####  Get supported Frequency from Calibration file  ###########
FREQ_MIN=$(sed -n ${FREQ_LINE}p $CAL_FNAME | cut -d " " -f 1)
FREQ_STP=$(sed -n ${FREQ_LINE}p $CAL_FNAME | cut -d " " -f 2)
FREQ_MAX=$(sed -n ${FREQ_LINE}p $CAL_FNAME | cut -d " " -f 3)

###############  Convert Decimal to Integer  ####################
RX_FREQ=$(echo ${RX_FREQ} | cut -d "." -f 1)

###############  Check Frequency argument  ######################
if [ ${RX_FREQ} -lt ${FREQ_MIN} ] || [ ${RX_FREQ} -gt ${FREQ_MAX} ]; then
    echo "$0 - Invalid frequency, out of range."
    >&2 usage
fi

############### Get Attenuation value postion  ##################
FRE_ARRAY_INDEX=$(expr $(expr $(expr ${RX_FREQ} - ${FREQ_MIN}) / ${FREQ_STP}) + 1)

################### Get Attenuation value########################
ATT_TO_SET=$(sed -n ${CAL_OFFSET_LINE}p $CAL_FNAME | cut -d " " -f ${FRE_ARRAY_INDEX})

echo $ATT_TO_SET
