#!/bin/sh

STARTUPCFG_DIR=
STARTUPCFG_DIR_DEFAULT=/etc

SYSCFG_FILE_NAME=system.conf
SYSCFG_DIR=
SYSCFG_DIR_DEFAULT=/tmp

TX_POWER=
TX_BW=
TX_POWER_DEFAULT=30

RX_BW=
RX_POWER=
RX_POWER_DEFAULT=30


usage(){
  echo "Usage
        $0 - Set Baseband attenuators, Enable Front-End devices and set Front-End attenuators with calibration files

SYNOPSIS
        $0 [OPTIONS] [OPTIONS Value] [-b 10] [-c /etc] ...

DESCRIPTION
        -h, --help
                Print this messages

        -b BW, --bw BW
                Bandwidth [5, 10, 20]

        -d DLEAR, --dlearfcn DLEAR
                Downlink Earfcn

        -u ULEAR, --ulearfcn ULEAR
                Uplink Earfcn

        -t FREQ, --txfreq FREQ
                TX Frequency

        -r FREQ, --rxfreq FREQ
                RX Frequency

        -p POW, --txpower POW
                TX Power (dBm)

        -c FILE, --config FILE
                (optional) Directory to get startup.cfg
                Default directory /etc

        -s FILE, --syscofig FILE
                (optional) Directory to get system.conf
                Default directory /tmp
"
    exit 1
}

while [ $# -gt 0 ] ; do
    case "$1" in
    -h | --help)
        usage
        exit 1
        ;;
    -b | --bw)
        shift;
        TX_BW="$1"
        RX_BW="$1"
        ;;
    -d | --dlearfcn)
        shift;
        DLEARFCN="$1"
        ;;
    -u | --ulearfcn)
        shift;
        ULEARFCN="$1"
        ;;
    -t | --txfreq)
        shift;
        TX_FREQ="$1"
        ;;
    -r | --rxfreq)
        shift;
        RX_FREQ="$1"
        ;;
    -p | --txpower)
        shift;
        TX_POWER="$1"
        ;;
    -c | --config)
        shift
        STARTUPCFG_DIR=$1
        ;;
    -s | --sysconfig)
        shift
        SYSCFG_DIR=$1
        ;;
    -* | --*)
        echo "$0 - No option: $1"
        usage
        exit 1
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

####################  Source system.conf  #######################
if [ ! -z $SYSCFG_DIR ] ; then
    if [ -f "$SYSCFG_DIR/$SYSCFG_FILE_NAME" ] ; then
        source "$SYSCFG_DIR/$SYSCFG_FILE_NAME"
    else
        echo "$0 - Error: can't stat system.conf file : No such file or directory"
        exit 1
    fi
elif [ -f $SYSCFG_DIR_DEFAULT/$SYSCFG_FILE_NAME ] ; then
    source $SYSCFG_DIR_DEFAULT/$SYSCFG_FILE_NAME
else
    echo "$0 - Error: can't stat system.conf file : No such file or directory"
    exit 1
fi

####################  Check System Mode  ########################
if [ ${MODE} != "e2e" ] ; then
    echo "$0 - Error: Invalid Mode! Please set to e2e mode!"
    exit 1
fi

####################  Check TX Frequency  #######################
if [ -z $TX_FREQ ] ; then
    if [ -z $DLEARFCN ] ; then
        #############  Check startup.cfg file  ##################
        if [ ! -z $STARTUPCFG_DIR ] ; then
            #########  Get DL Earfcn from startup.cfg file  #########
            TX_FREQ=$(bb-getfreq -d dl -c $STARTUPCFG_DIR 2> /dev/null)
            if [ $? -ne 0 ] ; then
                echo "$0 - Error Get Downlink Frequency : $TX_FREQ"
                exit 1
            fi
        else
            TX_FREQ=$(bb-getfreq -d dl -c $STARTUPCFG_DIR_DEFAULT 2> /dev/null)
            if [ $? -ne 0 ] ; then
                echo "$0 - Error Get Downlink Frequency : $TX_FREQ"
                exit 1
            fi
        fi
    else
        TX_FREQ=$(bb-getfreq -d dl -e $DLEARFCN 2> /dev/null)
        if [ $? -ne 0 ] ; then
            echo "$0 - Error Get Downlink Frequency : $TX_FREQ"
            exit 1
        fi
    fi
fi

TX_FREQ=$(echo ${TX_FREQ} | cut -d "." -f 1)

####################  Check RX Frequency  #######################
if [ -z $RX_FREQ ] ; then
    if [ -z $ULEARFCN ] ; then
        #############  Check startup.cfg file  ##################
        if [ ! -z $STARTUPCFG_DIR ] ; then
            #########  Get UL Earfcn from startup.cfg file  #########
            RX_FREQ=$(bb-getfreq -d ul -c $STARTUPCFG_DIR 2> /dev/null)
            if [ $? -ne 0 ] ; then
                echo "$0 - Error Get Uplink Frequency : $RX_FREQ"
                exit 1
            fi
        else
            RX_FREQ=$(bb-getfreq -d ul -c $STARTUPCFG_DIR_DEFAULT 2> /dev/null)
            if [ $? -ne 0 ] ; then
                echo "$0 - Error Get Uplink Frequency : $RX_FREQ"
                exit 1
            fi
        fi
    else
        RX_FREQ=$(bb-getfreq -d ul -e $ULEARFCN 2> /dev/null)
        if [ $? -ne 0 ] ; then
            echo "$0 - Error Get Uplink Frequency : $RX_FREQ"
            exit 1
        fi
    fi
fi

RX_FREQ=$(echo ${RX_FREQ} | cut -d "." -f 1)

#######################  Check BandWidth  #######################
if [ -z $TX_BW ] ; then
    TX_BW=${BW}
    RX_BW=${BW}
fi

#######################  Check TX Power  ########################
if [ -z $TX_POWER ] ; then
    TX_POWER=${TX_POWER_DEFAULT}
fi

#######################  Check RX Power  ########################

RX_POWER=${TX_POWER}  ################################ Test #########################
if [ -z $RX_POWER ] ; then
    RX_POWER=${RX_POWER_DEFAULT}
fi

#####################  Set BB TX Attenuation ####################
CAL_BB_ATT_TX1=$(cal-getbbtxatt ${TX_BW} 1 ${TX_FREQ} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Get BB Attenuation TX1: $CAL_BB_ATT_TX1"
    exit 1
fi

CAL_BB_ATT_TX2=$(cal-getbbtxatt ${TX_BW} 2 ${TX_FREQ} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Get BB Attenuation TX2: $CAL_BB_ATT_TX1"
    exit 1
fi


bb-settxatt 1 ${CAL_BB_ATT_TX1} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set BB Attenuation TX1"
    exit 1
fi

bb-settxatt 2 ${CAL_BB_ATT_TX2} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set BB Attenuation TX2"
    exit 1
fi


#####################  Set BB RX Attenuation ####################
CAL_BB_ATT_RX1=$(cal-getbbrxatt ${RX_BW} 1 ${RX_FREQ} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Get BB Attenuation RX1: $CAL_BB_ATT_RX1"
    exit 1
fi

CAL_BB_ATT_RX2=$(cal-getbbrxatt ${RX_BW} 2 ${RX_FREQ} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Get BB Attenuation RX2: $CAL_BB_ATT_RX1"
    exit 1
fi


bb-setrxatt 1 ${CAL_BB_ATT_RX1} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set BB Attenuation RX1"
    exit 1
fi

bb-setrxatt 2 ${CAL_BB_ATT_RX2} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set BB Attenuation RX2"
    exit 1
fi


##########################  Enable FE  ##########################
fe-enable 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Enable FE"
    exit 1
fi

#################  Set FE FB Attenuation  #######################
CAL_FE_FB_ATT_TX1=$(cal-getfefbatt ${TX_BW} 1 ${TX_FREQ} ${TX_POWER} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Get FE FB Attenuation TX1: $CAL_BB_ATT_TX1"
    exit 1
fi

CAL_FE_FB_ATT_TX2=$(cal-getfefbatt ${TX_BW} 2 ${TX_FREQ} ${TX_POWER} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Get FE FB Attenuation TX2: $CAL_BB_ATT_TX1"
    exit 1
fi


fe-setfbatt 1 ${CAL_FE_FB_ATT_TX1} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE FB Attenuation TX1"
    exit 1
fi

fe-setfbatt 2 ${CAL_FE_FB_ATT_TX2} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE FB Attenuation TX2"
    exit 1
fi

#################  Set FE TX Attenuation  #######################
CAL_FE_TX_ATT_TX1=$(cal-getfetxatt -b ${TX_BW} -a 1 -f ${TX_FREQ} -p ${TX_POWER} -t 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE TX Attenuation TX1: $CAL_BB_ATT_TX1"
    exit 1
fi

CAL_FE_TX_ATT_TX2=$(cal-getfetxatt -b ${TX_BW} -a 2 -f ${TX_FREQ} -p ${TX_POWER} -t 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE TX Attenuation TX2: $CAL_BB_ATT_TX1"
    exit 1
fi


fe-settxatt 1 ${CAL_FE_TX_ATT_TX1} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE TX Attenuation TX1"
    exit 1
fi

fe-settxatt 2 ${CAL_FE_TX_ATT_TX2} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE TX Attenuation TX2"
    exit 1
fi

####################  Reset RFPAL  ##############################
fe-resetrfpal


#################  Set FE RX Attenuation  #######################
CAL_FE_RX_ATT_RX1=$(cal-getferxatt -b ${RX_BW} -a 1 -f ${RX_FREQ} -p ${RX_POWER} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE RX Attenuation RX1: $CAL_BB_ATT_RX1"
    exit 1
fi

CAL_FE_RX_ATT_RX2=$(cal-getferxatt -b ${RX_BW} -a 2 -f ${RX_FREQ} -p ${RX_POWER} 2> /dev/null)
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE RX Attenuation RX2: $CAL_BB_ATT_RX1"
    exit 1
fi


fe-setrxatt 1 ${CAL_FE_RX_ATT_RX1} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE RX Attenuation RX1"
    exit 1
fi

fe-setrxatt 2 ${CAL_FE_RX_ATT_RX2} 2> /dev/null
if [ $? -ne 0 ] ; then
    echo "$0 - Error Set FE RX Attenuation RX2"
    exit 1
fi
