#!/bin/sh

source /tmp/system.conf

# Min and Max for all LTE bands using FDD
FREQ_MIN=$(expr 400 + ${BW} / 2)
FREQ_MAX=$(expr 3650 - ${BW} / 2)

usage()
{
	echo "usage: $0 <freq>"
	echo "  <freq>     TX Frequency in MHz"
	exit 1
}

if [ "$#" -ne 1 ]; then
	usage
fi

awk 'BEGIN{if ('$1'<'$FREQ_MIN') exit 1}'
if [ $? -eq 1 ]; then
	echo "Frequency is too low"
	exit 1
fi

awk 'BEGIN{if ('$1'>'$FREQ_MAX') exit 1}'
if [ $? -eq 1 ]; then
	echo "Frequency is too high"
	exit 1
fi

oncpu 0 /usr/bin/cn_rfdriver << eof > /dev/null
u
$1
q
eof
