#!/bin/sh

source /tmp/system.conf

# Min and Max for all LTE bands using FDD
FREQ_MIN=$(expr 400 + ${BW} / 2)
FREQ_MAX=$(expr 3650 - ${BW} / 2)

usage()
{
	echo "usage: $0 <freq>"
	echo "  <freq>     TX Frequency in MHz"
	exit 1
}

if [ "$#" -ne 1 ]; then
	usage
fi

if [ $1 -lt ${FREQ_MIN} ]; then
	echo "Frequency is too low"
	exit 1
elif [ $1 -gt ${FREQ_MAX} ]; then
	echo "Frequency is too high"
	exit 1
fi

oncpu 0 /usr/bin/cn_rfdriver << eof > /dev/null
d
$1
q
eof
