#!/bin/sh

source FE_Env

usage()
{
    echo "Usage: $0 <ANT>"
    echo ""
    echo "    Get Front-End TX attenuation"
    echo ""
    echo "    <ANT>     Antenna selection [1,2]"
    exit 1
}

if [ "$#" -ne 1 ]; then
    >&2 usage
fi

if [ $1 -ne "1" ] && [ $1 -ne "2" ]; then
    echo "$0 - Invalid antenna selection."
    >&2 usage
fi


if [ $1 -eq "1" ]; then
    echo $(cat ${RX0_ATT})
else
    echo $(cat ${RX1_ATT})
fi
