SRC_URI += " \
            file://0001-RFC-fsck-Allow-to-specify-the-fsck-repair-option-in-.patch \
            file://0001-journal-fix-hashmap-leak-in-mmap-cache.patch \
            file://0001-journald-fix-minor-memory-leak.patch \
            file://0001-journald-accept-EPOLLERR-from-dev-kmsg.patch \
            file://0001-journal-fix-minor-memory-leak.patch \
            file://0001-Fix-memory-leak-in-stdout-journal-streams.patch \
	"
