# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

INCLUDES += -I./include \
		-I$(FWDIR)/lib/include \
		-I$(FWDIR)/lib/cryptolib/include \
		-I../common/include \
		-I../utility/include \
		-I../misclibs/include

BUILD_ROOT := ${BUILD}/vkernel

ALL_SRCS = kernel_image.c

include ../common.mk

