#!/usr/bin/perl -w

# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

#
#	File: tc_led
#
#	This test case LED program uses the fbt(1) program to run
#	the $Cled test sequence against the LED card. Since the LED
#	card needs manual intervention, it is best run as a separate
#	test. The tests that can be fully automated can be segregated
#	so they may be run repetitively without operator intervention.
#
use strict;

$ENV{FBT_TEST_TABLE_INDEX}	= 4;
my $Prog			= '/usr/local/fbin/fbt';
my $Arg				= '-l';
exec($Prog, $Arg);
