// ************* active interaction function *****************
var activeInteraction = document.getElementById('activeInteraction');
activeInteraction.style.width = '22px';
activeInteraction.innerHTML = '<span><i class="fas fa-mouse-pointer"></i></span>';
activeInteraction.setAttribute('data-original-title', 'Active Tool - Measure Area');
activeInteraction.style.display = 'block';

// *****************************************************
function setActiveInteraction(e = null, interactionName, active) {
    if (e) { e.stopPropagation(); }
    highlightLayer.setStyle(highlightStyle);
    if (actionRunning) {
        selectPolygon.setActive(false);
        drawPolygon.setActive(false);
        modifyPolygon.setActive(false);
        transformPolygon.setActive(false);
        deletePolygonActive = false;
        snapPolygon.setActive(false);
        selectSite.setActive(false);
        drawSite2G.setActive(false);
        drawSite4G.setActive(false);
        modifySite.setActive(false);
        deleteSiteActive = false;
        snapSite.setActive(false);
        addLink.setActive(false);
        selectLink.setActive(false);
        drawLink.setActive(false);
        deleteLinkActive = false;
        snapLink.setActive(false);
        selectNote.setActive(false);
        drawNote.setActive(false);
        modifyNote.setActive(false);
        deleteNoteActive = false;
        snapNote.setActive(false);
        select.setActive(false);
        measureLine.setActive(false);
        measureArea.setActive(false);
        activeInteraction.style.width = '22px';
        activeInteraction.innerHTML = '';
        activeInteraction.setAttribute('data-original-title', '');
        activeInteraction.style.display = 'none';
        return;
    }
    switch (interactionName) {
        case 'drawPolygon':
            selectPolygon.setActive(false);
            drawPolygon.setActive(active);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-draw-polygon" style="color: rgb(127,58,183);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-edit"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Draw Polygon');
            activeInteraction.style.display = 'block';
            break;
        case 'modifyPolygon':
            selectPolygon.setActive(active);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(active);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(active);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            selectLink.setActive(false);
            addLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-draw-polygon" style="color: rgb(127,58,183);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-external-link-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Modify Polygon');
            activeInteraction.style.display = 'block';
            break;
        case 'transformPolygon':
            selectPolygon.setActive(active);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(active);
            deletePolygonActive = false;
            snapPolygon.setActive(active);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-draw-polygon" style="color: rgb(127,58,183);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-retweet"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Transform Polygon');
            activeInteraction.style.display = 'block';
            break;
        case 'deletePolygon':
            highlightLayer.setStyle(deletePolygonStyle);
            selectPolygon.setActive(active);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = active;
            snapPolygon.setActive(active);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-draw-polygon" style="color: rgb(127,58,183);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-trash-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Delete Polygon');
            activeInteraction.style.display = 'block';
            break;
        case 'drawLink':
            highlightLayer.setStyle(drawLinkSiteStyle);
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(active);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-link" style="color: rgb(127,58,183);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-edit"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Draw Link');
            activeInteraction.style.display = 'block';
            break;
        case 'deleteLink':
            highlightLayer.setStyle(deleteLinkStyle);
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(active);
            drawLink.setActive(false);
            deleteLinkActive = active;
            snapLink.setActive(active);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-link" style="color: rgb(127,58,183);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-trash-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Delete Link');
            activeInteraction.style.display = 'block';
            break;
        case 'drawSite2G':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(active);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-broadcast-tower" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-edit"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Draw Site');
            activeInteraction.style.display = 'block';
            break;
        case 'drawSite4G':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(active);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-broadcast-tower" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-edit" style="color:rgb(255,106,0);"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Draw Site');
            activeInteraction.style.display = 'block';
            break;
        case 'modifySite':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(active);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(active);
            deleteSiteActive = false;
            snapSite.setActive(active);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-broadcast-tower" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-external-link-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Modify Site');
            activeInteraction.style.display = 'block';
            break;
        case 'deleteSite':
            highlightLayer.setStyle(deleteSiteStyle);
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(active);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = active;
            snapSite.setActive(active);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-broadcast-tower" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-trash-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Delete Site');
            activeInteraction.style.display = 'block';
            break;
        case 'drawNote':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(active);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-flag" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-edit"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Draw Note');
            activeInteraction.style.display = 'block';
            break;
        case 'modifyNote':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(active);
            drawNote.setActive(false);
            modifyNote.setActive(active);
            deleteNoteActive = false;
            snapNote.setActive(active);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-flag" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-external-link-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Modify Note');
            activeInteraction.style.display = 'block';
            break;
        case 'deleteNote':
            highlightLayer.setStyle(deleteNoteStyle);
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(active);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = active;
            snapNote.setActive(active);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(false);
            activeInteraction.style.width = '55px';
            activeInteraction.innerHTML = '<span><i class="fas fa-flag" style="color: rgb(33,163,246);"></i></span>&nbsp;-&nbsp;<span><i class="fas fa-trash-alt"></i></span>';
            activeInteraction.setAttribute('data-original-title', 'Active Tool - Delete Note');
            activeInteraction.style.display = 'block';
            break;
        case 'toggleSelect':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(active);
            measureLine.setActive(false);
            measureArea.setActive(false);
            if (active) {
                activeInteraction.style.width = '22px';
                activeInteraction.innerHTML = '<span><i class="fas fa-mouse-pointer"></i></span>';
                activeInteraction.setAttribute('data-original-title', 'Active Tool - Select');
                activeInteraction.style.display = 'block';
            } else {
                activeInteraction.style.width = '22px';
                activeInteraction.innerHTML = '';
                activeInteraction.setAttribute('data-original-title', '');
                activeInteraction.style.display = 'none';
            }
            break;
        case 'toggleMeasureLine':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(!measureLine.getActive());
            measureArea.setActive(false);
            if (measureLine.getActive()) {
                activeInteraction.style.width = '22px';
                activeInteraction.innerHTML = '<span><i class="fas fa-ruler"></i></span>';
                activeInteraction.setAttribute('data-original-title', 'Active Tool - Measure Line');
                activeInteraction.style.display = 'block';
            } else {
                activeInteraction.style.width = '22px';
                activeInteraction.innerHTML = '';
                activeInteraction.setAttribute('data-original-title', '');
                activeInteraction.style.display = 'none';
            }
            break;
        case 'toggleMeasureArea':
            selectPolygon.setActive(false);
            drawPolygon.setActive(false);
            modifyPolygon.setActive(false);
            transformPolygon.setActive(false);
            deletePolygonActive = false;
            snapPolygon.setActive(false);
            selectSite.setActive(false);
            drawSite2G.setActive(false);
            drawSite4G.setActive(false);
            modifySite.setActive(false);
            deleteSiteActive = false;
            snapSite.setActive(false);
            addLink.setActive(false);
            selectLink.setActive(false);
            drawLink.setActive(false);
            deleteLinkActive = false;
            snapLink.setActive(false);
            selectNote.setActive(false);
            drawNote.setActive(false);
            modifyNote.setActive(false);
            deleteNoteActive = false;
            snapNote.setActive(false);
            select.setActive(false);
            measureLine.setActive(false);
            measureArea.setActive(!measureArea.getActive());
            if (measureArea.getActive()) {
                activeInteraction.style.width = '22px';
                activeInteraction.innerHTML = '<span><i class="fas fa-ruler-combined"></i></span>';
                activeInteraction.setAttribute('data-original-title', 'Active Tool - Measure Area');
                activeInteraction.style.display = 'block';
            } else {
                activeInteraction.style.width = '22px';
                activeInteraction.innerHTML = '';
                activeInteraction.setAttribute('data-original-title', '');
                activeInteraction.style.display = 'none';
            }
            break;
    }
    clearInteractions();
}
function clearInteractions() {
    select.getFeatures().clear();
    selectPolygon.getFeatures().clear();
    selectSite.getFeatures().clear();
    selectLink.getFeatures().clear();
    selectNote.getFeatures().clear();
    addLink.getFeatures().clear(); pointCount = 0; siteASelected = undefined;
    transformPolygon.getFeatures().clear();
    transformPolygon.setActive(!transformPolygon.getActive());
    transformPolygon.setActive(!transformPolygon.getActive());
    highlightLayer.getSource().clear();
    highlightFeature = undefined;
    featureInfo.innerHTML = '';
    featureInfo.style.opacity = 0;
    noteInfo.innerHTML = '';
    noteInfo.style.opacity = 0;
    //featureTip.attr('data-original-title', '').tooltip('hide');
}
function toggleSelect() {
    setActiveInteraction(null, 'toggleSelect', true);
    setActiveInteraction(null, 'toggleSelect', true);
}